### ISSUE TITLE
Test A1

### ISSUE THREAD

**Issue by PascalBouchez** [maximeg44/M2L#1]
Les salles ne sont pas triés par capacité ou catégorie.
Ils manquent également les horaires d'ouvertures.
Existence de boutons "Modifier" ainsi que d'un bouton pour "Ajouter une nouvelle salle".

**Comment by SullivanRoirand** [comment]
https://github.com/maximeg44/M2L/commit/196c097a8e1debcd73e308790fe7f280768ce438
